// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/tmp2/go-metrics/internal/usecases/metric_get_by_id_path.go

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	domain "go-metrics/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricGetByIDPathService is a mock of MetricGetByIDPathService interface.
type MockMetricGetByIDPathService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricGetByIDPathServiceMockRecorder
}

// MockMetricGetByIDPathServiceMockRecorder is the mock recorder for MockMetricGetByIDPathService.
type MockMetricGetByIDPathServiceMockRecorder struct {
	mock *MockMetricGetByIDPathService
}

// NewMockMetricGetByIDPathService creates a new mock instance.
func NewMockMetricGetByIDPathService(ctrl *gomock.Controller) *MockMetricGetByIDPathService {
	mock := &MockMetricGetByIDPathService{ctrl: ctrl}
	mock.recorder = &MockMetricGetByIDPathServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricGetByIDPathService) EXPECT() *MockMetricGetByIDPathServiceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockMetricGetByIDPathService) GetByID(ctx context.Context, id *domain.MetricID) (*domain.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMetricGetByIDPathServiceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMetricGetByIDPathService)(nil).GetByID), ctx, id)
}
