// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/go-metrics/go-metrics/internal/services/metric_list.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	domain "go-metrics/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricListFindBatchRepository is a mock of MetricListFindBatchRepository interface.
type MockMetricListFindBatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricListFindBatchRepositoryMockRecorder
}

// MockMetricListFindBatchRepositoryMockRecorder is the mock recorder for MockMetricListFindBatchRepository.
type MockMetricListFindBatchRepositoryMockRecorder struct {
	mock *MockMetricListFindBatchRepository
}

// NewMockMetricListFindBatchRepository creates a new mock instance.
func NewMockMetricListFindBatchRepository(ctrl *gomock.Controller) *MockMetricListFindBatchRepository {
	mock := &MockMetricListFindBatchRepository{ctrl: ctrl}
	mock.recorder = &MockMetricListFindBatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricListFindBatchRepository) EXPECT() *MockMetricListFindBatchRepositoryMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockMetricListFindBatchRepository) Find(ctx context.Context, filters []domain.MetricID) (map[domain.MetricID]*domain.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filters)
	ret0, _ := ret[0].(map[domain.MetricID]*domain.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMetricListFindBatchRepositoryMockRecorder) Find(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMetricListFindBatchRepository)(nil).Find), ctx, filters)
}
